### ISSUE TITLE
Build of sapl-demo-reactive is failing

### ISSUE THREAD

**Issue by nniikkoollaaii** [heutelbeck/sapl-demos#41] opened 2021-07-06 19:39 UTC
Hello @heutelbeck , 

the build of the sapl-demo-reactive component is failing. Probably due to your version bump this afternoon?

This is since some change you introduced somewhere triggering this build:

<https://github.com/heutelbeck/sapl-demos/actions/runs/1005360953>

Could you please have a look?

**Comment by heutelbeck** [comment] 2021-07-07 13:20
Caused by a bad dependency setting in the new sapl-generator module unrelated to my pushes. I pushed a fix to the engine.

**Closed by heutelbeck** 2021-07-07 13:20 UTC
